name: Accessibility Validation

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "**"

jobs:
    build:
        runs-on: windows-2019

        steps:
            - uses: actions/checkout@v2

            # Insert any jobs here required to build your website files

            - name: Scan for accessibility issues
              uses: brocktaylor7/ai-action-gh-test@main
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  # Provide either site-dir or url
                  site-dir: ${{ github.workspace }}/public
                  # url: your-website-url
                  scan-url-relative-path: "//"

            - name: Upload report artifact
              uses: actions/upload-artifact@v2
              with:
                  name: accessibility-reports
                  path: ${{ github.workspace }}/_accessibility-reports
