name: Accessibility Validation

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            # Insert any jobs here required to build your website files

            - name: Scan for accessibility issues
              uses: brocktaylor7/ai-action-gh-test@main
              with:
                  # Provide either static-site-dir or url
                  static-site-dir: ${{ github.workspace }}/public
                  # url: your-website-url
                  # static-site-url-relative-path: "/"
                  fail-on-accessibility-error: false

            - name: Upload report artifact
              if: success() || failure()
              uses: actions/upload-artifact@v2
              with:
                  name: accessibility-reports
                  path: ${{ github.workspace }}/_accessibility-reports
